apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demohpa
spec:
  maxReplicas: 20
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
  targetCPUUtilizationPercentage: 40
