apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demors
  namespace: demons
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: r1
        image: nginx
