apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demopvc
  # namespace: demons
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
